# Generated by Django 6.0.6 on 2026-06-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrived', models.DateField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField(default=0)),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
