# Generated by Django 6.0.6 on 2026-06-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_dealer_item_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='dealer_add',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='dealer_phNo',
            field=models.IntegerField(blank=True, max_length=12, null=True),
        ),
    ]
