# Generated by Django 5.2.5 on 2026-06-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_dealer_dealer_add_dealer_dealer_phno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='members',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
