# Generated by Django 5.2.5 on 2026-06-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_dealer_id_alter_item_id_alter_members_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='dealer_email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
